services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: acefactory
    container_name: acefactory-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - acefactory-network

  db:
    image: mysql:8.3.0
    container_name: acefactory-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - acefactory-network

  nginx:
    image: nginx:alpine
    container_name: acefactory-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - acefactory-network

networks:
  acefactory-network:
    driver: bridge
